#!/usr/bin/env python
"""
Provides methods for interacting with WSDLs and Apex related to the FuseIT SFDC Explorer WSDL2Apex tool
"""

import re

def fix_classes(class_paths):
    """
    Fixes inconsistencies in Apex classes generated by the WSDL2Apex tool provided in FuseIT's SFDC Explorer

    - Adds the type name to the info array for each inner class's member
    - Adds the namespace to the info array for each inner class's member
    - Removes the transient keyword from each private member (info arrays)
    - Removes single line comments
    """
    def member_type_info_repl(match_obj):
        return f"{match_obj.group(1)}{match_obj.group(2)}{match_obj.group(3)}{match_obj.group(2)}{match_obj.group(4)}http://EFX.integration.fiserv.com/V1_0{match_obj.group(5)}"

    pattern_repl_dict = {
        r"(private transient String\[\] )([a-zA-Z0-9]+)(_type_info = new String\[\]{')(',')(','','.*','.*'};)": member_type_info_repl,
        r"transient ": ''
    }

    for cls_path in class_paths:
        cls_txt = ''
        with open(cls_path, 'r') as cls_file:
            cls_txt = cls_file.read()
        for pattern,repl in pattern_repl_dict.items():
            cls_txt = re.sub(pattern,repl,cls_txt)
        with open(cls_path, 'w') as cls_file:
            cls_file.write(cls_txt)